---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright 2016, IBM US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# apt packages needed for lxc support
apt_packages:
  - apt-transport-https
  - wget
  - curl
  - rsync
  - python-pip

jre_apt_repo_url: "http://ftp.us.debian.org/debian"

jre_apt_repos:
  - { repo: "deb {{ jre_apt_repo_url }} experimental main", state: "present" }
  - { repo: "deb {{ jre_apt_repo_url }} sid main", state: "present" }

elasticsearch_system_user: elasticsearch
elasticsearch_system_group: elasticsearch

jre_apt_package: openjdk-7-jre-headless

elasticsearch_pip_packages:
  - elasticsearch
  - elasticsearch-curator

#preq for openjdk-7-jre-headless can't be found with apt-get
elasticsearch_preq_deb_packages:
  - { url: "http://ftp.us.debian.org/debian/pool/main/libj/libjpeg-turbo", file: "libjpeg62-turbo_1.5.1-2_ppc64el.deb" }

#for ppc64le and x86 use the deb package to install
elasticsearch_deb_packages:
  - { url: "https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.1", file: "elasticsearch-2.4.1.deb" }

# This sets the cluster name
elasticsearch_cluster: openstack

# This sets the default HTTP port to listen on
elasticsearch_http_port: 9200

# This sets the default TCP port to listen on
elasticsearch_tcp_port: 9300

# Change this to 'true' will ensure that elasticsearch never uses swap space
elasticsearch_bootstrap_mlockall: "false"

# Change this to override the default value (which is 50% of total memory)
# elasticsearch_heap_size_mb: 1024

# Change this to override the default value (which is the same value as
# elasticsearch_heap_size_mb). if mlockall is set to true this setting
# is intentionally set to 'unlimited' instead.
# elasticsearch_max_locked_memory_mb: 1024

# This sets the retention period for data in ElasticSearch
elasticsearch_prune_days: 90

# Note that this effectively disables the distributed features
# If you're expanding beyond one node these should be adjusted
elasticsearch_index_number_of_shards: 1
elasticsearch_index_number_of_replicas: 0
