---
# Copyright 2016, IBM US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apt_packages:
  - build-essential
  - python-pip
  - python-dev
  - libssl-dev
  - libffi-dev
  - mysql-client
  - python-mysqldb
  - rsync

pip_packages:
  - pbr
  - setuptools
  - pymysql
  - pycrypto
  - paramiko
  - sqlalchemy
  - stevedore
  - pyyaml
  - enum-compat
  - configparser

opsmgr_modules:
  - opsmgr
  - opsmgr/horizon
  - opsmgr/plugins/devices/powernode
  - opsmgr/plugins/devices/ubuntu
  - opsmgr/plugins/devices/mellanox
  - opsmgr/plugins/devices/lenovo
  - opsmgr/plugins/devices/rhel
  - opsmgr/plugins/operations/elk
#  - opsmgr/plugins/operations/ganglia
  - opsmgr/plugins/operations/nagios
  - opsmgr/plugins/discovery/cobbler
  - opsmgr/plugins/hooks/ulysses

tmp_dir: /tmp/sync

old_pip_packages:
  - pbr>=1.9
  - setuptools>=20.3.1
  - pymysql>=0.7.4
  - pycrypto>=2.6.1
  - paramiko>=1.16.0
  - sqlalchemy>=1.0.12
  - stevedore>=1.12.0
  - pyyaml>=3.11
  - enum-compat>=0.0.2
  - configparser>=3.5.0b2

